language: python

os: linux

sudo: required

services:
  - docker

before_install:
  - if [[ "$RUN_DOCKER" == "yes" ]]; then docker pull iotjs/js_remote_test:0.4; fi

install:
  - pip install pylint

script: "tools/travis_script.py $OPTS"

env:
  matrix:
    - OPTS="--check-signoff"
    - OPTS="--check-pylint"
    - OPTS="--device=rpi2 --app=iotjs" RUN_DOCKER=yes
    - OPTS="--device=rpi2 --app=jerryscript" RUN_DOCKER=yes
    - OPTS="--device=artik530 --app=iotjs" RUN_DOCKER=yes
    - OPTS="--device=artik530 --app=jerryscript" RUN_DOCKER=yes
    - OPTS="--device=artik053 --app=iotjs" RUN_DOCKER=yes
    - OPTS="--device=artik053 --app=jerryscript" RUN_DOCKER=yes
    - OPTS="--device=stm32f4dis --app=iotjs" RUN_DOCKER=yes
    - OPTS="--device=stm32f4dis --app=jerryscript" RUN_DOCKER=yes
